namespace Waystone.Common.Api.SwaggerDocument;

using NJsonSchema;
using NSwag;
using NSwag.Generation.Processors;
using NSwag.Generation.Processors.Contexts;

public class AddCorrelationIdHeaderParameter : IOperationProcessor
{
    private readonly string _headerName;

    public AddCorrelationIdHeaderParameter(string headerName)
    {
        _headerName = headerName;
    }

    /// <inheritdoc />
    public bool Process(OperationProcessorContext context)
    {
        context.OperationDescription.Operation.Parameters.Add(new OpenApiHeader
        {
            Name = _headerName,
            Kind = OpenApiParameterKind.Header,
            Type = JsonObjectType.String,
            Description = "The correlation id to be associated with the request. One will be generated by the API if not provided.",
            IsRequired = false,
        });

        return true;
    }
}
