namespace Waystone.Common.Api.SwaggerDocument;

using NJsonSchema;
using NSwag;
using NSwag.Generation.Processors;
using NSwag.Generation.Processors.Contexts;

/// <summary>A processor for adding the correlation id header parameter.</summary>
internal class AddCorrelationIdHeaderParameter : IOperationProcessor
{
    private readonly string _headerName;

    /// <summary>Initializes a new instance of the <see cref="AddCorrelationIdHeaderParameter" /> class.</summary>
    /// <param name="headerName">The header name.</param>
    public AddCorrelationIdHeaderParameter(string headerName)
    {
        _headerName = headerName;
    }

    /// <inheritdoc />
    public bool Process(OperationProcessorContext context)
    {
        context.OperationDescription.Operation.Parameters.Add(
            new OpenApiHeader
            {
                Name = _headerName,
                Kind = OpenApiParameterKind.Header,
                Schema = new JsonSchema
                {
                    Type = JsonObjectType.String,
                    Format = JsonFormatStrings.Guid,
                    Example = "72b264f5-d6e9-4e74-a6ce-d398e2c8421a",
                },
                Description =
                    "The correlation id to be associated with the request. One will be generated by the API if not provided.",
                IsRequired = false,
            });

        return true;
    }
}
